language: node_js
node_js:
- 5.3.0
install:
- npm install
script:
- webpack -p --bail --progress --build
sudo: false
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $DEV_AWS_KEY
  secret_access_key: $DEV_AWS_SECRET
  bucket: accounts.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: accounts.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: accounts.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  # DEV_AWS_KEY
  - secure: "sYDL87vOCmqGjxXwyfRLldnv464aFqvqGZV15Nkj81nsaOsP1x/N1qHiYETSm34i/iO/jCk38MlSovzEQE/6BGv6LVrt6URC05RabJQglyag9nNdBkoVQPL/Ic0+4BTqARU8q57f0tjFfBeVkR3/r3sVrboWTKbjBXyEnpGUXautjj9zJIk91qsj55UJaFZodxIMK1a7WujG2LH/1fVGw6dOXN8d12ZqvTuIZq2DJ1eIpTcjJ3cq+xDz1O5EUnvC2O9c28mf3o7vKTrmLsa2BdbZoXhWHfgZk7n0QU1Wp677oaQdHp6WJPyPDSbpEpdGjmTaWB/vkF1yKVeSUhiYuqnLWX8n897mik2oKMa9aY+y4WlLDlBhgqZJeFurLJ9O+ThUYhCqt8qeHv2YADabJAil42dk0EgX2rJUKkE/eCOWZOdMB2OZAFTbp6qF/M8N5XmE2aPszZfWxHZreRr+qcCDhwK43DromvZwHxqCFyYJ33xwMD1gNtsxkvCResRDlCMmVVMXoFxdDScyqLWM6pQnkauY45gxWr//B0gWdsBOCUbroeq0LwO2mYYRf9fzC69t7C0nzo/ye79vaiCF37fqCb/0MNVZaugqgL4710Tw10Ees39482oTxL3p/oUfQZbWLmkauUcehP/7vvlhvKWA7y8HNe7azZo+ksmRfCY="
  # DEV_AWS_SECRET
  - secure: "iV97tGe23h5cv/pus6aZ+zj2PozdE+zNA1t7/ZJoKn2bRs6MJoc1i0pFAhM/HFuettOSfARKh13XM3MvzfTVlf/TgK1/KfHsooJ7QulkKYnBSW62Ran5+Wg63i3M9phBs48hkuoDfLr2ECuUvn5fRWZfNJECKl7A2n7cLnNv7DyP5Q/VJYx4QFQ6Kdlbox4CaCJrkYkzDDYVGdx7PT+KCCCzaDfnfn9iUViEkcvy3b06zCrqrSblQGUimFzw3+uJs6iS0L/acJC6HxtnF1cl8mAS2v+6pRIhS2X2t9mOGagkhy8rB3Z506epPHMOM5vO5hp4YxMSPZCSbCAaTlxgkl4ECeYWStsKcb5mgTi8s28kQYU9zKcLx1hFzwLtReQhLj3AAjBwmB8BdYXCnHxkHi/uWTMQYEXtn6XWZs29fTUemSHua6vpOQcr/8ZJV1p7Jkd5Fv424D2xjWSCmxdscuN83WFO3ENdUOJCPlAN437IKk9tYdLX7m0UBX/8Dprn0ShN1hlTndx3X+EPzFChsdftZhexrsRv/5GvkDCtrjUFU4EBptUSYRVK10jFa2cervByFpcABeGyaXlOQDIQjtVpuQE7tOEiiJlrNKFBYH3o4ZKUD3n42oJtNDjCh5NHchaNLICzjlJoA5U2ADfMkfs6ivmp0BdVIC4rfGLevzA="
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
