version: 2
jobs:
  "build-dev":
    docker:
      - image: node:5.10.1
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - build-dev
          filters:
            branches:
              only: dev-circleci2      

	  
  
